In [238]:

import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager"
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame({
    "emp_id": emp_ids,
    "emp_age": emp_ages,
    "emp_salary": emp_income,
    "role": emp_roles
})

# Save dataset
data.to_csv("staff_data.csv", index=False)

In [ ]:
emp_age = np.array([emp_ages])

print(emp_age)
print(type(emp_age))
print(emp_age.ndim)
print(emp_age.dtype)
print("Total number of elements: ",emp_age.shape[1])

emp_in = np.array([emp_income])
print(emp_in)
print(type(emp_in))
print(emp_in.ndim)
print(emp_in.dtype)
print("Total number of elements: ",emp_in.shape[1])

[[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
  53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
  31 50]]
<class 'numpy.ndarray'>
2
int32
Total number of elements:  50
[[51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
  56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
  60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
  94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
  59727 50398]]
<class 'numpy.ndarray'>
2
int32
Total number of elements:  50

In [40]:
salary = np.array([emp_income])
max_salary = np.max(salary)
min_salary = np.min(salary)
mean_salary = np.mean(salary)
print('maximum salary: ', max_salary)
print('minimum salary: ', min_salary)
print("average salary: ",mean_salary)

ages = np.array([emp_ages])
mean_age = np.mean(ages)
print("average age: ", mean_age)

maximum salary:  94722
minimum salary:  35452
average salary:  68409.48
average age:  35.44

In [143]:
emp_age = np.array(emp_ages)
emp_salary = np.array(emp_income)
aged_b_25_t_40 = np.where((emp_age >= 25) & (emp_age <= 40))
more_inc_than_50k = np.where(emp_salary >= 50000)
count = np.count_nonzero(more_inc_than_50k)
total_emp_age = len(aged_b_25_t_40[0])
total_emp_salary =len(more_inc_than_50k[0])

print('are aged between 25 and 40: ',total_emp_age)
print('have salary greater than 50,000: ',total_emp_salary)
print("total employs: ",total_emp_age + total_emp_salary)

are aged between 25 and 40:  19
have salary greater than 50,000:  43
total employs:  62

In [145]:
emp_age = np.array(emp_ages)
mean_ages = np.mean(emp_age)
adjust_ages = np.where(emp_age > mean_age , emp_age + 2, emp_age + 4)


print('original array: ',emp_age)
print('updated array: ',adjust_ages)
print("average age: ",mean_age)

original array:  [54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
updated array:  [56 27 24 45 39 39 25 39 28 40 35 39 33 40 31 47 53 50 24 36 53 55 25 30
 55 39 30 25 47 34 24 49 55 55 27 28 25 34 31 29 41 24 49 43 26 54 44 56
 35 52]
average age:  35.44

In [186]:
emp_role = np.array(emp_roles)
emp_salary = np.array(emp_income)
tech_roles = np.where((emp_role == "Backend Developer") | (emp_role == "Digital Marketer") | (emp_role == "Software Developer" ))
present_salary = emp_salary[tech_roles]
salary_increase = np.where(present_salary > 0, (present_salary * 1.08),0)
total_present_salary = np.sum(present_salary)
new_total_salary = np.sum(salary_increase)


print("new total salary expense: ",new_total_salary)
print('overall increase in expense: ', new_total_salary - total_present_salary)

new total salary expense:  1408510.08
overall increase in expense:  104334.08000000007

In [ ]:
df = pd.read_csv('./staff_data.csv')
first_3_row = df.head(3)
print(first_3_row)
first_3_row.info()
first_3_row.describe()

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      3 non-null      int64
 1   emp_age     3 non-null      int64
 2   emp_salary  3 non-null      int64
 3   role        3 non-null      str
dtypes: int64(3), str(1)
memory usage: 266.0 bytes

       emp_id    emp_age    emp_salary
count     3.0   3.000000      3.000000
mean    102.0  32.333333  41890.666667
std       1.0  18.823744   8651.621023
min     101.0  20.000000  35452.000000
25%     101.5  21.500000  36973.500000
50%     102.0  23.000000  38495.000000
75%     102.5  38.500000  45110.000000
max     103.0  54.000000  51725.000000

In [32]:
df =  pd.read_csv('./staff_data.csv')
get_selected_data = df[["emp_id",'emp_age','role']]

get_selected_age = df.loc[(df['emp_age'] < 40) & (df['emp_age'] > 25)] 

get_sorted_data = get_selected_age.sort_values('emp_id')
get_sorted_data

    emp_id  emp_age  emp_salary                 role
4      105       37       72187    Backend Developer
5      106       37       58915           HR Manager
7      108       35       92864      Sales Executive
9      110       38       90494         HR Executive
10     111       31       68641    Backend Developer
11     112       35       48079  Marketing Executive
12     113       29       56879      Sales Executive
13     114       38       83682   Operations Manager
14     115       27       94722     Digital Marketer
19     120       32       74146    Backend Developer
23     124       26       78354   Software Developer
25     126       37       79898   Operations Manager
26     127       26       59682     Digital Marketer
29     130       30       73700           Accountant
37     138       30       84188           Accountant
38     139       27       52013           HR Manager
40     141       39       44396  Marketing Executive
48     149       31       59727     Digital Marketer

In [ ]:
df =  pd.read_csv('./staff_data.csv')
Hr_role_list = df.loc[df['role'] == 'HR Manager']
print(Hr_role_list)
print('Total number of HR employees: ',len(Hr_role_list))

    emp_id  emp_age  emp_salary        role
0      101       54       51725  HR Manager
5      106       37       58915  HR Manager
38     139       27       52013  HR Manager
45     146       52       41061  HR Manager
Total number of HR employees:  4

In [121]:
df =  pd.read_csv('./staff_data.csv')
sorted_by_age_salary = df.sort_values(['emp_age', 'emp_salary'], ascending=[1, 0])
sorted_by_age_salary.head(5).loc[:,['emp_id', 'emp_salary', 'role']]

    emp_id  emp_salary                role
30     131       82550     Sales Executive
18     119       63187  Software Developer
41     142       59500    Digital Marketer
2      103       35452  Operations Manager
36     137       94427     Sales Executive

In [330]:
df = pd.read_csv('./staff_data.csv')
c = df.copy()
emp_role_S_B = c.loc[(c['role'] == "Software Developer") |( c['role'] == 'Backend Developer')]
emp_role_Others = c.loc[(c['role'] != "Software Developer") & (c['role'] != 'Backend Developer')]

emp_role_S_B_12 = emp_role_S_B.loc[:, 'emp_salary'] * 1.12
emp_role_Others_5 = emp_role_Others.loc[:, 'emp_salary'] * 1.05 

c = c.loc[:, ['role','emp_salary']]
new_salary =pd.concat([emp_role_S_B_12, emp_role_Others_5]).sort_index()

c['new_salary'] = new_salary
c['increase_of_salary'] = new_salary - c['emp_salary']
new_df = c.rename(columns={'emp_salary': 'previous_salary'})
new_df
# c['emp_salary'] = (c.loc[(c['role'] == 'Software Developer')|(c['role'] == 'Backend Developer'), 'emp_salary' ] * 1.12 ) | (c.loc[(c['role'] != 'Software Developer')&(c['role'] != 'Backend Developer'), 'emp_salary' ] * 1.05)
# c['emp_salary'] = c.loc[c['role'] == 'Backend Developer','emp_salary'] * 1.12

                   role  previous_salary  new_salary  increase_of_salary
0            HR Manager            51725    54311.25             2586.25
1            Accountant            38495    40419.75             1924.75
2    Operations Manager            35452    37224.60             1772.60
3      Digital Marketer            82295    86409.75             4114.75
4     Backend Developer            72187    80849.44             8662.44
5            HR Manager            58915    61860.75             2945.75
6     Backend Developer            76159    85298.08             9139.08
7       Sales Executive            92864    97507.20             4643.20
8       Sales Executive            76155    79962.75             3807.75
9          HR Executive            90494    95018.70             4524.70
10    Backend Developer            68641    76877.92             8236.92
11  Marketing Executive            48079    50482.95             2403.95
12      Sales Executive            56879    59722.95             2843.95
13   Operations Manager            83682    87866.10             4184.10
14     Digital Marketer            94722    99458.10             4736.10
15    Financial Analyst            91041    95593.05             4552.05
16      Sales Executive            48899    51343.95             2444.95
17   Operations Manager            68744    72181.20             3437.20
18   Software Developer            63187    70769.44             7582.44
19    Backend Developer            74146    83043.52             8897.52
20      Sales Executive            75641    79423.05             3782.05
21      Sales Executive            47678    50061.90             2383.90
22           Accountant            76760    80598.00             3838.00
23   Software Developer            78354    87756.48             9402.48
24         HR Executive            60584    63613.20             3029.20
25   Operations Manager            79898    83892.90             3994.90
26     Digital Marketer            59682    62666.10             2984.10
27         HR Executive            71888    75482.40             3594.40
28   Software Developer            51086    57216.32             6130.32
29           Accountant            73700    77385.00             3685.00
30      Sales Executive            82550    86677.50             4127.50
31  Marketing Executive            71447    75019.35             3572.35
32     Digital Marketer            76100    79905.00             3805.00
33    Backend Developer            72269    80941.28             8672.28
34   Software Developer            73314    82111.68             8797.68
35   Software Developer            87428    97919.36            10491.36
36      Sales Executive            94427    99148.35             4721.35
37           Accountant            84188    88397.40             4209.40
38           HR Manager            52013    54613.65             2600.65
39      Sales Executive            63326    66492.30             3166.30
40  Marketing Executive            44396    46615.80             2219.80
41     Digital Marketer            59500    62475.00             2975.00
42         HR Executive            55523    58299.15             2776.15
43           Accountant            58602    61532.10             2930.10
44         HR Executive            90794    95333.70             4539.70
45           HR Manager            41061    43114.05             2053.05
46   Software Developer            82331    92210.72             9879.72
47   Software Developer            73048    81813.76             8765.76
48     Digital Marketer            59727    62713.35             2986.35
49  Marketing Executive            50398    52917.90             2519.90